# Generated by Django 4.0.6 on 2022-08-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_products_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
